name: Build Clash Rules

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download & Merge Clash YAML Rules
        run: |
          mkdir -p dist tmp
          urls=(
            "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml"
            "https://raw.githubusercontent.com/REIJI007/AdBlock_Rule_For_Clash/main/adblock_reject.yaml"
            "https://anti-ad.net/clash.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyList.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyPrivacy.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml"
            "https://hub.gitmirror.com/raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
          )

          > tmp/merged.txt
          for url in "${urls[@]}"; do
            curl -sSL --retry 3 "$url" >> tmp/merged.txt || echo "Failed $url"
            echo "" >> tmp/merged.txt
          done

          # 只保留规则行并去重
          grep -E '^(DOMAIN-SUFFIX|DOMAIN-KEYWORD|DOMAIN|IP-CIDR|IP-CIDR6),' tmp/merged.txt | sort -u > tmp/unique-rules.txt

          # 规则总数
          total_rules=$(wc -l < tmp/unique-rules.txt)

          # 输出最终 YAML，添加头部信息
          OUTPUT="dist/merged-clash.yaml"
          {
            echo "# ======================================="
            echo "# Clash Rules - 自动生成"
            echo "# 生成时间: $(date -u '+%Y-%m-%d %H:%M UTC')"
            echo "# 规则总数: $total_rules"
            echo "# ======================================="
            echo ""
            cat tmp/unique-rules.txt
          } > $OUTPUT

          echo "RELEASE_TAG=clash-rules-$(date -u +'%Y%m%d')" >> $GITHUB_ENV

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dist/merged-clash.yaml

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Clash rules: $(date -u '+%Y-%m-%d')"
            git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin main
          fi
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Clash 规则更新"
          body: "本次规则自动生成更新，总规则数: $total_rules"
          files: |
            dist/merged-clash.yaml

      - name: Show Rules Stats
        run: |
          echo "================= Clash Rules Stats ================="
          echo "Merged total rules: $total_rules"
          head -n 20 dist/merged-clash.yaml
          echo "====================================================="
