name: Clean AdGuard Blocklists

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install dnspython requests

      - name: Clean all sources
        run: python clean_blocklist.py

      - name: Upload merged blocklist
        uses: actions/upload-artifact@v3
        with:
          name: blocklist_valid_merged
          path: blocklist_valid_merged.txt
