name: Process Whitelist

on:
  push:
    paths:
      - 'dist/whitelist.txt'   # 监控whitelist.txt文件的变动
  pull_request:
    paths:
      - 'dist/whitelist.txt'   # 监控PR中whitelist.txt文件的变动
  schedule:
    - cron: "0 8,14,20,2 * * *"  # 每天的 08:00、14:00、20:00 和次日 02:00 (UTC+8时间)

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 下载 whitelist.txt 文件
      - name: Download whitelist.txt
        run: |
          echo "Downloading whitelist.txt from GitHub"
          curl -o dist/whitelist.txt https://raw.githubusercontent.com/wxglenovo/AdGuardHome-Filter/refs/heads/main/dist/whitelist.txt

      # 3. 使用 Shell 脚本处理 whitelist.txt 文件
      - name: Process whitelist.txt using shell script
        run: |
          echo "Processing whitelist.txt"
          
          # 创建一个临时文件存储最终结果
          TEMP_FILE="dist/processed_whitelist.txt"
          touch $TEMP_FILE

          # 遍历 whitelist.txt 中的域名
          while IFS= read -r line; do
            domain=$(echo $line | tr -d '[:space:]')  # 去除空格

            # 如果该域名已经存在于处理结果中，则跳过
            if grep -qx "$domain" $TEMP_FILE; then
              continue
            fi

            # 逐层检查是否有父域已在文件中，如果有，跳过当前子域
            parts=($(echo "$domain" | tr '.' ' '))  # 分割域名为数组
            domain_level=${#parts[@]}

            for ((i=1; i<$domain_level; i++)); do
              parent_domain=$(echo "${parts[@]:$i}" | tr ' ' '.')
              if grep -qx "$parent_domain" $TEMP_FILE; then
                continue 2  # 如果父域已在文件中，跳过该子域
              fi
            done

            # 将域名写入处理结果文件
            echo $domain >> $TEMP_FILE

          done < dist/whitelist.txt

      # 4. 提交处理后的 whitelist 文件
      - name: Commit processed whitelist.txt
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'Update processed whitelist.txt'
          add: 'dist/processed_whitelist.txt'

      # 5. 输出工作流运行的日志
      - name: Show completed processing message
        run: echo "Processing complete. The processed whitelist.txt has been updated."
