name: Clean AdGuardHome Rules

on:
  schedule:
    # 每天 0 点、15 分、30 分、45 分执行（UTC 时区）
    - cron: "0 0,15,30,45 0 * * *"   # 每天午夜（UTC）
    - cron: "0 0,15,30,45 6 * * *"   # 每天 6 点（UTC）
    - cron: "0 0,15,30,45 12 * * *"  # 每天 12 点（UTC）
    - cron: "0 0,15,30,45 18 * * *"  # 每天 18 点（UTC）
  workflow_dispatch:         # 支持手动触发

permissions:
  contents: write

jobs:
  clean_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download whitelist.txt
        run: |
          curl -o whitelist.txt https://raw.githubusercontent.com/wxglenovo/AdGuardHome-Filter/refs/heads/main/dist/whitelist.txt

      - name: Process rules to remove redundant subdomains
        run: |
          cat whitelist.txt | awk '{print $1}' | sort | uniq > sorted_whitelist.txt
          awk '{
            split($1, parts, ".")
            domain = parts[length(parts)-1] "." parts[length(parts)]
            print domain
          }' sorted_whitelist.txt | sort | uniq > final_whitelist.txt

      - name: Commit the cleaned whitelist
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "YourName"
          git add final_whitelist.txt
          git commit -m "Cleaned whitelist by removing redundant subdomains"
          git push
