#!/bin/bash

# 下载 whitelist.txt 文件
curl -o whitelist.txt https://raw.githubusercontent.com/wxglenovo/AdGuardHome-Filter/refs/heads/main/dist/whitelist.txt

# 创建一个临时文件存储处理结果
TEMP_FILE="processed_whitelist.txt"
> $TEMP_FILE  # 清空文件

# 处理 whitelist.txt 文件
while IFS= read -r line; do
    domain=$(echo $line | tr -d '[:space:]')  # 去除空格

    # 跳过空行
    if [ -z "$domain" ]; then
        continue
    fi

    # 分割域名为数组，按 '.' 分隔
    parts=($(echo "$domain" | tr '.' ' '))

    # 获取域名的层级数
    domain_level=${#parts[@]}

    # 遍历处理已经出现过的父域
    skip=false
    for ((i=1; i<$domain_level; i++)); do
        parent_domain=$(echo "${parts[@]:$i}" | tr ' ' '.')
        
        # 如果父域已经存在于临时文件中，跳过该子域
        if grep -qx "$parent_domain" $TEMP_FILE; then
            skip=true
            break
        fi
    done

    # 如果没有跳过，加入临时文件
    if [ "$skip" = false ]; then
        echo $domain >> $TEMP_FILE
    fi

done < whitelist.txt

# 输出处理完成的文件
echo "Processed whitelist.txt saved to $TEMP_FILE"
cat $TEMP_FILE  # 查看最终结果

# 提交处理后的文件
git add $TEMP_FILE
git commit -m "Processed whitelist to remove redundant subdomains"
git push origin main
