permissions:
  contents: write

jobs:
  clean_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download whitelist.txt
        run: |
          curl -o whitelist.txt https://raw.githubusercontent.com/wxglenovo/AdGuardHome-Filter/refs/heads/main/dist/whitelist.txt

      - name: Process rules to remove redundant subdomains
        run: |
          # 读取原始 whitelist.txt
          cat whitelist.txt | awk '{print $1}' | sort | uniq > sorted_whitelist.txt
          
          # 处理规则，保留父域（例如www.example.com -> example.com）
          awk '{
            split($1, parts, ".")
            domain = parts[length(parts)-1] "." parts[length(parts)]
            print domain
          }' sorted_whitelist.txt | sort | uniq > final_whitelist.txt

      - name: Commit the cleaned whitelist
        run: |
          # 配置 git 用户信息
          git config --global user.email "youremail@example.com"
          git config --global user.name "YourName"

          # 添加生成的 final_whitelist.txt 文件到 Git
          git add final_whitelist.txt

          # 检查是否有修改的内容，如果有就提交
          git diff --cached --exit-code || git commit -m "Cleaned whitelist by removing redundant subdomains"

          # 推送更改到远程仓库
          git push
